################################################################################
# 
# Copyright(c) 2008 Texas Instruments, Inc. All rights reserved.
# 
# This program is free software; you can redistribute it and/or modify it 
# under the terms of the GNU General Public License as published by the Free 
# Software Foundation; either version 2 of the License, or (at your option) 
# any later version.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT 
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for 
# more details.
# 
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 
# Temple Place - Suite 330, Boston, MA  02111-1307, USA.
# 
# The full GNU General Public License is included in this distribution in the
# file called LICENSE.
# 
################################################################################

# *************************************************************************
# * Makefile Wrapper file for building syslog.
# *************************************************************************

# Include this file that contains definitions.
-include $(TARGET_HOME)/TI_Build.make

INSTALL=install

all: build install

build:
	$(MAKE) CC=$(CROSS)gcc syslogd syslog_tst

install: 
	$(INSTALL) -m 0755 syslogd $(TI_filesystem_path)$(TI_rsbindir)/ti_syslogd
# UNIHAN ADD START
	$(INSTALL) -m 0644 syslog.conf $(TI_filesystem_basefs_path)$(TI_etcdir)/
# UNIHAN ADD END

clean: 
	$(MAKE) clean
	rm -f $(TI_filesystem_path)$(TI_rsbindir)/ti_syslogd
