########################################################
#
#   Example configuration file for the MLD Proxy
#   --------------------------------------------
#
#   The configuration file must define one WAN side Upstream
#   interface, and one or more LAN side Downstream interfaces.
#   
#   In cablelabs terms, Upstream is operator faced inteface,
#   Downstream ia a customer faced interface (or interfaces), 
#   i.e. interfaces connecting CPE
#   If multicast traffic originates outside the
#   upstream subnet, #
#   The "fastleave" should be used to avoid saturation
#   of the upstream link. The option should only
#   be used if it's absolutely nessecary to
#   accurately imitate just one Client.
#
########################################################

##------------------------------------------------------
## Enable Fastleave mode (Sends Leave instantly)
##------------------------------------------------------
fastleave


##------------------------------------------------------
## Configuration for erouter0 (Upstream Interface WAN side)
##------------------------------------------------------
phyint erouter0 upstream llqi 3000  


##------------------------------------------------------
## Configuration for eth0 (Downstream Interface LAN side)
##------------------------------------------------------
phyint rndbr1 downstream  llqi 3000 llqc 4 fastleave 


##------------------------------------------------------
## Configuration for wifi0 (Disabled Interface)
##------------------------------------------------------
#phyint wifi0 disabled


