# 
#  GPL LICENSE SUMMARY
#
#  Copyright(c) 2012 Intel Corporation.
#
#  This program is free software; you can redistribute it and/or modify 
#  it under the terms of version 2 of the GNU General Public License as
#  published by the Free Software Foundation.
#
#  This program is distributed in the hope that it will be useful, but 
#  WITHOUT ANY WARRANTY; without even the implied warranty of 
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU 
#  General Public License for more details.
#
#  You should have received a copy of the GNU General Public License 
#  along with this program; if not, write to the Free Software 
#  Foundation, Inc., 51 Franklin St - Fifth Floor, Boston, MA 02110-1301 USA.
#  The full GNU General Public License is included in this distribution 
#  in the file called LICENSE.GPL.
#
#  Contact Information:
#    Intel Corporation
#    2200 Mission College Blvd.
#    Santa Clara, CA  97052
#

# *************************************************************************
# * Makefile Wrapper file for building e2fsprogs
# *************************************************************************

ifndef CURDIR
CURDIR=$(shell pwd)
endif

PACKAGE_VERSION := 1.42.6
PACKAGE_DIR := e2fsprogs-$(PACKAGE_VERSION)
PACKAGE_CONF := \
        --host=armeb-buildroot-linux-uclibcgnueabi \
        --enable-fsck \
        --prefix=$(CURDIR)/$(PACKAGE_DIR)/execfiles \
        --exec-prefix=$(CURDIR)/$(PACKAGE_DIR)/execfiles \
        --disable-nls \
        --disable-rpath \
        --with-gnu-ld \

first_rule: all

all: build install

$(CURDIR)/$(PACKAGE_DIR)/build/Makefile:
	@mkdir $(CURDIR)/$(PACKAGE_DIR)/build 
	@mkdir $(CURDIR)/$(PACKAGE_DIR)/execfiles 
	@cd $(CURDIR)/$(PACKAGE_DIR)/intl && cp plural.c.orig plural.c
	@cd $(CURDIR)/$(PACKAGE_DIR)/build && ../configure $(PACKAGE_CONF)

build: $(CURDIR)/$(PACKAGE_DIR)/build/Makefile
	@cd $(CURDIR)/$(PACKAGE_DIR)/build && make

config_rule: $(CURDIR)/$(PACKAGE_DIR)/build/Makefile

install_rule install:
	@cd $(CURDIR)/$(PACKAGE_DIR)/build && make install
	install -p $(CURDIR)/$(PACKAGE_DIR)/execfiles/sbin/fsck.ext3 $(TI_filesystem_path)/sbin

clean_rule distclean clean:
	rm -f $(TI_filesystem_path)/sbin/fsck.ext3
	rm -rf $(CURDIR)/$(PACKAGE_DIR)/build  
	rm -rf $(CURDIR)/$(PACKAGE_DIR)/execfiles  
	rm -f $(CURDIR)/$(PACKAGE_DIR)/intl/plural.c

