################################################################################
# 
# Copyright(c) 2008 Texas Instruments, Inc. All rights reserved.
# 
# This program is free software; you can redistribute it and/or modify it 
# under the terms of the GNU General Public License as published by the Free 
# Software Foundation; either version 2 of the License, or (at your option) 
# any later version.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT 
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for 
# more details.
# 
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 
# Temple Place - Suite 330, Boston, MA  02111-1307, USA.
# 
# The full GNU General Public License is included in this distribution in the
# file called LICENSE.
# 
################################################################################

-include $(TARGET_HOME)/TI_Build.make
-include $(TARGET_HOME)/.config

all: build install

build:
	$(MAKE) all

install:
	@#ARRIS CHANGE - preserve timestamps
	install -p -m 0644 oop.h $(TARGET_HOME)/ti/include
	@#END ARRIS CHANGE
	install -m 0644 liboop.a $(TARGET_HOME)/ti/lib

clean:
	$(MAKE) clean
	rm -f  $(TARGET_HOME)/ti/include/oop.h
	rm -f  $(TARGET_HOME)/ti/lib/liboop.a

