! Host name and password for ripd console
! Connect to port 2602 start the ripd console
hostname TID30PUMA5
password JhAkuo18

! Enable RIP v2 send, accept v1 and v2.
router rip
version_send 2
version_rev 2

! Define passive and non-passive interfaces
passive-interface default
no passive-interface
! no passive-interface br0 (enable to test on br0)

! Define network interfaces
network erouter0

! Default metric
default-metric

! Timers
timers basic

! Redistribute list
!redistribute kernel 
redistribute static
redistribute connected

distribute-list private in erouter0
distribute-list public  out erouter0
