! Host name and password for ripng console
! Connect to port 2603 start the ripng console
hostname RIPNG
password JhAkuo18
!

router ripng
!  network erouter0
!  distribute-list private in erouter0
!  distribute-list public out erouter0
!
!ipv6 access-list local-only permit 3ffe:506::0/32
!ipv6 access-list local-only deny any

