################################################################################
# 
# Copyright(c) 2008 Texas Instruments, Inc. All rights reserved.
# 
# This program is free software; you can redistribute it and/or modify it 
# under the terms of the GNU General Public License as published by the Free 
# Software Foundation; either version 2 of the License, or (at your option) 
# any later version.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT 
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for 
# more details.
# 
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 
# Temple Place - Suite 330, Boston, MA  02111-1307, USA.
# 
# The full GNU General Public License is included in this distribution in the
# file called LICENSE.
# 
################################################################################

# *************************************************************************
# * Makefile Wrapper file for building 7-Zip Utility.
# *************************************************************************

# Tools:
RM=@rm
CC=@gcc
CXX=@c++
CFLAGS=-O2 -m32
TARGET=7zip
all: build install

config:

build: $(TARGET)

$(TARGET): LZMAEncoder.o 7zip.o
	$(CXX) $(CFLAGS) -o 7zip LZMAEncoder.o 7zip.o

LZMAEncoder.o: LZMA/LZMAEncoder.cpp 
	$(CC) $(CFLAGS) -c LZMA/LZMAEncoder.cpp

7zip.o: 7zip.c
	$(CC) $(CFLAGS) -c 7zip.c

install: build
	@install -m 0755 $(TARGET) $(TI_tools_path)/bin

uninstall:
	@rm -f $(TI_tools_path)/bin/$(TARGET)

clean: uninstall
	$(RM) -f *.o
	$(RM) -f 7zip

distclean: clean
