################################################################################
# 
# Copyright(c) 2008 Texas Instruments, Inc. All rights reserved.
# 
# This program is free software; you can redistribute it and/or modify it 
# under the terms of the GNU General Public License as published by the Free 
# Software Foundation; either version 2 of the License, or (at your option) 
# any later version.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT 
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for 
# more details.
# 
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 
# Temple Place - Suite 330, Boston, MA  02111-1307, USA.
# 
# The full GNU General Public License is included in this distribution in the
# file called LICENSE.
# 
################################################################################

# *************************************************************************
# * Makefile Wrapper file for building Configuration Utilities.
# *************************************************************************

-include $(TARGET_HOME)/TI_Build.make

all: build install

config:

build: config
	$(MAKE) all

install: build
	install -m 0755 conf $(TI_tools_path)/bin
	install -m 0755 mconf $(TI_tools_path)/bin
	install -m 0755 lxdialog/lxdialog $(TI_tools_path)/bin
	if [ -f qconf ]; then \
	  install -m 0755 qconf $(TI_tools_path)/bin ;\
	fi
	(cd $(TI_tools_path)/bin; ln -sf qconf qbuild)

uninstall:
	-rm -f $(TI_tools_path)/bin/conf $(TI_tools_path)/bin/mconf $(TI_tools_path)/bin/qconf $(TI_tools_path)/bin/qbuild  $(TI_tools_path)/lxdialog

clean: uninstall
	$(MAKE) clean

distclean: clean

.PHONY: all config build install uninstall clean distclean
