#
# Makefile Wrapper file for building udev utility
#
# Copyright (C) 2008 Texas Instruments Incorporated - http://www.ti.com/ 
# 
# 
#  Redistribution and use in source and binary forms, with or without 
#  modification, are permitted provided that the following conditions 
#  are met:
#
#    Redistributions of source code must retain the above copyright 
#    notice, this list of conditions and the following disclaimer.
#
#    Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the 
#    documentation and/or other materials provided with the   
#    distribution.
#
#    Neither the name of Texas Instruments Incorporated nor the names of
#    its contributors may be used to endorse or promote products derived
#    from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
#  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
#  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
#  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT 
#  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT 
#  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
#  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE 
#  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

-include $(TARGET_HOME)/TI_Build.make
-include $(TARGET_HOME)/.config

all: build install

config:

build: config
	$(MAKE) CROSS_COMPILE=$(CROSS_TOOLS) CONFIG_ARM_THUMB=$(CONFIG_ARM_THUMB)

install: build
	install -m 0755 udev $(TI_filesystem_path)/sbin
	install -m 0755 udevstart $(TI_filesystem_path)/sbin
	install -m 0755 udevd $(TI_filesystem_path)/sbin
	install -m 0755 udevsend $(TI_filesystem_path)/sbin

uninstall:
	-rm -f $(TI_filesystem_path)/sbin/udev
	-rm -f $(TI_filesystem_path)/sbin/udevstart
	-rm -f $(TI_filesystem_path)/sbin/udevd
	-rm -f $(TI_filesystem_path)/sbin/udevsend

clean: uninstall
	$(MAKE) clean

distclean: clean

.PHONY: all config build install uninstall clean distclean
