################################################################################
# 
# Copyright(c) 2008 Texas Instruments, Inc. All rights reserved.
# 
# This program is free software; you can redistribute it and/or modify it 
# under the terms of the GNU General Public License as published by the Free 
# Software Foundation; either version 2 of the License, or (at your option) 
# any later version.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT 
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for 
# more details.
# 
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 
# Temple Place - Suite 330, Boston, MA  02111-1307, USA.
# 
# The full GNU General Public License is included in this distribution in the
# file called LICENSE.
# 
################################################################################

# *************************************************************************
# * Makefile Wrapper file for building  XZ Utilities.
# *************************************************************************

-include $(TARGET_HOME)/TI_Build.make

CC = gcc

XzLib = $(TI_tools_path)/lib/liblzma.a

${XzLib}:
	./configure --prefix=$(TARGET_HOME)/tools --enable-static
	$(MAKE) all
	$(MAKE) install

all: ${XzLib} 

config:
	./configure --prefix=$(TARGET_HOME)/tools --enable-static

build: config
	$(MAKE) all

install: build
	$(MAKE) install
uninstall:
	$(MAKE) uninstall	

clean: uninstall
	$(MAKE) clean

distclean: clean

.PHONY: all config build install uninstall clean distclean
